### PR TITLE
hacked in 'console'

### PR DESCRIPTION
**Pull request by jschoch**
I have no idea what i'm doing so.... i guess this is a decent test to see if VS2019 automagic changes impact your install.

The changes add a "console" window that autoscrolls to the last message line.

If you like it I can add "command history" next, seems like something I might be able to manage in c# land.

### CODE REVIEW

**Comment by jschoch** [comment]
also i saw your v4 but it didn't look like you pushed your commits up yet.  did i miss something?

**Comment by terjeio** [comment]
v4 commits are up, the latest  one - "Improved button interlocks, added direct transfer for Vectric apps".

**Comment by terjeio** [comment]
VS2015 was not happy with this, there are references to files that are missing (Probing) and bunch of other stuff I have to look into. References to missing files were quick to fix, the rest not so.

**Comment by terjeio** [comment]
I've taken a look at your code - not too bad!

A couple of points: by "console" I understand that as where the responses from grbl should be displayed. You have hooked the messages property into ExecuteMDI which is what I would call "command log" or "MDI log", am I wrong in assuming that? - english is not my first language...

Also, ExecuteMDI may pass single character realtime commands to grbl, not obvious I know, but they will not display in a meaningful way. I guess I have misused ExecuteMDI by calling it from other controls than the MDI - I should add another command, perhaps ExecuteCommand for them. My bad.

What do you think about the right sidebar buttons for jogging and macros? Is this a good way to add functionality and to avoid clutter? Could it be a place to add a console view or is this something you keep an eye at often requiring it to be visible at all times?

**Comment by jschoch** [comment]
Sorry, my computer has been crashing so much it is hard to get anything straight.  I'll fix the pull with the missing files.

**Comment by jschoch** [comment]
should i add packages.config and packages (directories) to gitignore?

**Comment by terjeio** [comment]
> should i add packages.config and packages (directories) to gitignore?

Honestly I do not know - perhaps I have to move to VS2019  as well? Currently there is no room on my system disk for that, and I am not prepared to uninstall 2015 as it is the paid for Professional version (I use it for some commercial projects). If you do not use/need VS2019 for other projects then perhaps easier for you to switch to 2015?

**Comment by jschoch** [comment]
i had to restore from backup last night.  my system is a bit more stable today (fingers crossed).

the restore blew out my VS2019 anyway.  I think I know why vscode was having issues.  I may give that another try, digging into grblHAL today though and not sure when i'll get  back to this.  I want to get the external jogging working first.

**Pull request closed without merging**
